"""Canonical driver event envelope and event-name declarations.

Authoritative source:
- docs/ADR-driver-evolution-foundation.md#30-versioned-event-envelope-now
- docs/ADR-driver-evolution-foundation.md#188-resolved-decisions
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final, Literal, TypeAlias

JSONScalar: TypeAlias = str | int | float | bool | None
JSONValue: TypeAlias = JSONScalar | dict[str, "JSONValue"] | list["JSONValue"]
EventData: TypeAlias = dict[str, JSONValue]
DecideEventName: TypeAlias = Literal["DECIDE"]
FinalEventName: TypeAlias = Literal["FINAL"]
StepCompletedEventName: TypeAlias = Literal["STEP_COMPLETED"]
DriverLifecycleEventName: TypeAlias = Literal["DRIVER_LIFECYCLE"]
PlannerDispatchProgressEventName: TypeAlias = Literal["PLANNER_DISPATCH_PROGRESS"]
RecoveryVisibilityEventName: TypeAlias = Literal["RECOVERY_VISIBILITY"]
HeartbeatProgressEventName: TypeAlias = Literal["HEARTBEAT_PROGRESS"]

ANOMALY_VERDICT: Final = "ANOMALY_VERDICT"
AGENT_SELECTION_ERROR: Final = "AGENT_SELECTION_ERROR"
COLD_CONTEXT_VERDICT: Final = "COLD_CONTEXT_VERDICT"
COMPLETE_ACTION_IGNORED: Final = "COMPLETE_ACTION_IGNORED"
CONTINUITY_DOUBLE_TRUTH_DETECTED: Final = "CONTINUITY_DOUBLE_TRUTH_DETECTED"
DECIDE: Final = "DECIDE"
DRIVER_LIFECYCLE: Final = "DRIVER_LIFECYCLE"
ESCALATION_DEFERRED: Final = "ESCALATION_DEFERRED"
ESCALATION_VERDICT: Final = "ESCALATION_VERDICT"
FAILURE_REMEDIATION_DEFERRED: Final = "FAILURE_REMEDIATION_DEFERRED"
FAILURE_VERDICT: Final = "FAILURE_VERDICT"
FINAL: Final = "FINAL"
GATE_REMEDIATION_DEFERRED: Final = "GATE_REMEDIATION_DEFERRED"
GATE_VERDICT: Final = "GATE_VERDICT"
HALT: Final = "HALT"
HALT_REQUESTED: Final = "HALT_REQUESTED"
HEARTBEAT_PROGRESS: Final = "HEARTBEAT_PROGRESS"
JUDGE_FAILURE_POLICY: Final = "JUDGE_FAILURE_POLICY"
JUDGMENT: Final = "JUDGMENT"
MERGE_COMPLETED: Final = "MERGE_COMPLETED"
MERGE_CONFLICTED: Final = "MERGE_CONFLICTED"
PLANNER_DISPATCH_COMPLETED: Final = "PLANNER_DISPATCH_COMPLETED"
PLANNER_DISPATCH_FAILED: Final = "PLANNER_DISPATCH_FAILED"
PLANNER_DISPATCH_PROGRESS: Final = "PLANNER_DISPATCH_PROGRESS"
PLANNER_DISPATCH_STARTED: Final = "PLANNER_DISPATCH_STARTED"
PREFLIGHT_DEFER: Final = "PREFLIGHT_DEFER"
PREFLIGHT_REJECT: Final = "PREFLIGHT_REJECT"
PREFLIGHT_SKIPPED: Final = "PREFLIGHT_SKIPPED"
PREFLIGHT_VERDICT: Final = "PREFLIGHT_VERDICT"
RECOVERY: Final = "RECOVERY"
RECOVERY_VISIBILITY: Final = "RECOVERY_VISIBILITY"
RUNNER_FALLBACK: Final = "RUNNER_FALLBACK"
SESSION_REUSE_HIT: Final = "SESSION_REUSE_HIT"
SESSION_REUSE_MISS: Final = "SESSION_REUSE_MISS"
STARTUP_HYGIENE_BLOCKED: Final = "STARTUP_HYGIENE_BLOCKED"
STARTUP_HYGIENE_CLASSIFY: Final = "STARTUP_HYGIENE_CLASSIFY"
STARTUP_HYGIENE_QUARANTINE: Final = "STARTUP_HYGIENE_QUARANTINE"
STARTUP_HYGIENE_SCAN: Final = "STARTUP_HYGIENE_SCAN"
STARTUP_RECOVERY_DECISION: Final = "STARTUP_RECOVERY_DECISION"
STEP_COMPLETED: Final = "STEP_COMPLETED"
STEP_DISPATCHED: Final = "STEP_DISPATCHED"
STEP_FAILED: Final = "STEP_FAILED"
WAIT: Final = "WAIT"

ALL_EVENT_TYPES: Final[tuple[str, ...]] = (
    AGENT_SELECTION_ERROR,
    ANOMALY_VERDICT,
    COLD_CONTEXT_VERDICT,
    COMPLETE_ACTION_IGNORED,
    CONTINUITY_DOUBLE_TRUTH_DETECTED,
    DECIDE,
    DRIVER_LIFECYCLE,
    ESCALATION_DEFERRED,
    ESCALATION_VERDICT,
    FAILURE_REMEDIATION_DEFERRED,
    FAILURE_VERDICT,
    FINAL,
    GATE_REMEDIATION_DEFERRED,
    GATE_VERDICT,
    HALT,
    HALT_REQUESTED,
    HEARTBEAT_PROGRESS,
    JUDGE_FAILURE_POLICY,
    JUDGMENT,
    MERGE_COMPLETED,
    MERGE_CONFLICTED,
    PLANNER_DISPATCH_COMPLETED,
    PLANNER_DISPATCH_FAILED,
    PLANNER_DISPATCH_PROGRESS,
    PLANNER_DISPATCH_STARTED,
    PREFLIGHT_DEFER,
    PREFLIGHT_REJECT,
    PREFLIGHT_SKIPPED,
    PREFLIGHT_VERDICT,
    RECOVERY,
    RECOVERY_VISIBILITY,
    RUNNER_FALLBACK,
    SESSION_REUSE_HIT,
    SESSION_REUSE_MISS,
    STARTUP_HYGIENE_BLOCKED,
    STARTUP_HYGIENE_CLASSIFY,
    STARTUP_HYGIENE_QUARANTINE,
    STARTUP_HYGIENE_SCAN,
    STARTUP_RECOVERY_DECISION,
    STEP_COMPLETED,
    STEP_DISPATCHED,
    STEP_FAILED,
    WAIT,
)


@dataclass(frozen=True)
class Event:
    """Canonical driver event envelope for JSONL sinks."""

    ts: float
    event: str
    version: int = 1
    data: EventData = field(default_factory=dict)
