"""
Orchestration plane package.

Authority: docs/ORCHESTRATION-PLANE-IMPLEMENTATION-DESIGN.md section 2
Authority: docs/ORCHESTRATION-PLANE-INTERFACES.md sections 3-5
"""

from vectl.orchestration.contracts import (
    BarrierReason,
    ChildRunKind,
    ChildRunRef,
    ChildRunStatus,
    ControlDecision,
    CoreSnapshot,
    DispatchSpec,
    DriveBarrier,
    DriveRecord,
    DriveStatus,
    ExecutionRequest,
    ExecutionResult,
    IsolationMode,
    OpenCodeLaunchConfig,
    PlannerBundleStatus,
    PlannerMutationAction,
    PlannerMutationBundle,
    PlannerMutationItem,
    PlannerRequest,
    PromptArtifactPaths,
    PromptBundle,
    ReconcileResult,
    RecoveredVia,
    RecoveryAttempt,
    RecoveryContinuity,
    RequestMode,
    ResolutionCase,
    ResolutionCaseSource,
    ResolutionReport,
    RoleProfile,
    RosterSnapshot,
    RunnerHandoffEnv,
    RuntimeSnapshot,
    SessionPolicy,
    StructuredReviewResult,
    WorkLease,
    WorktreeBinding,
)
from vectl.orchestration.core_adapter import CoreAdapter
from vectl.orchestration.dispatch_policy import (
    ConfigPromptRegistry,
    ConfigRoleProfileRegistry,
    DispatchCoordinator,
    ReviewResultParseError,
    UnknownRoleError,
    normalize_parse_failure,
    normalize_review_result,
    step_verify_to_verify_mode,
)
from vectl.orchestration.interfaces import (
    Control,
    PlannerAdapter,
    Resolver,
    Roster,
    Runtime,
)
from vectl.orchestration.recovery_fallback import (
    RecoveryFallbackResult,
    SessionValidationResult,
    persist_recovery_attempt,
    persist_recovery_continuity,
    persist_recovery_fallback_result,
    read_recovery_attempt,
    read_recovery_continuity,
    recover_with_fallback,
    validate_session_for_resume,
)
from vectl.orchestration.resolution_reports import (
    parse_resolution_report_payload,
    validate_resolution_report_payload,
)
from vectl.orchestration.step_data import StepData

__all__ = [
    # Shared boundary types (contracts.py)
    "CoreSnapshot",
    "RosterSnapshot",
    "RuntimeSnapshot",
    "ControlDecision",
    "DispatchSpec",
    "IsolationMode",
    "WorkLease",
    "ExecutionRequest",
    "ExecutionResult",
    "RecoveryAttempt",
    "RecoveryContinuity",
    "RecoveredVia",
    "RequestMode",
    "SessionPolicy",
    "RoleProfile",
    "PromptArtifactPaths",
    "PromptBundle",
    "RunnerHandoffEnv",
    "OpenCodeLaunchConfig",
    "StructuredReviewResult",
    "ReconcileResult",
    "ResolutionCase",
    "ResolutionCaseSource",
    "ResolutionReport",
    "WorktreeBinding",
    # Drive scheduling types (contracts.py)
    "BarrierReason",
    "ChildRunKind",
    "ChildRunRef",
    "ChildRunStatus",
    "DriveBarrier",
    "DriveRecord",
    "DriveStatus",
    "PlannerBundleStatus",
    "PlannerMutationAction",
    "PlannerMutationBundle",
    "PlannerMutationItem",
    "PlannerRequest",
    # Core authority bridge contract (core_adapter.py)
    "CoreAdapter",
    # Component interfaces (interfaces.py)
    "Control",
    "PlannerAdapter",
    "Roster",
    "Runtime",
    "Resolver",
    # Dispatch policy (dispatch_policy.py)
    "ConfigRoleProfileRegistry",
    "ConfigPromptRegistry",
    "DispatchCoordinator",
    "StepData",
    "UnknownRoleError",
    "ReviewResultParseError",
    "normalize_review_result",
    "normalize_parse_failure",
    "step_verify_to_verify_mode",
    "parse_resolution_report_payload",
    "validate_resolution_report_payload",
    # Recovery fallback (recovery_fallback.py)
    "RecoveryFallbackResult",
    "SessionValidationResult",
    "persist_recovery_attempt",
    "persist_recovery_continuity",
    "persist_recovery_fallback_result",
    "read_recovery_attempt",
    "read_recovery_continuity",
    "recover_with_fallback",
    "validate_session_for_resume",
]
